# generated by datamodel-codegen:
#   filename:  https://testnet.iscc.id/api/v1/openapi.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class API(BaseModel):
    openapi: Optional[str] = Field("/api/v1/openapi.json", title="Openapi")
    version: Optional[str] = Field("0.1.0", title="Version")
    docs: Optional[str] = Field("/api/v1/docs", title="Docs")


class Forecast(BaseModel):
    iscc_id: Optional[str] = Field(
        None,
        description="ISCC-ID",
        example="ISCC:MMAOHZYGQLBASTFM",
        max_length=73,
        min_length=15,
        regex="^ISCC:[A-Z2-7]{10,73}$",
        title="Iscc Id",
    )
    chain_id: Optional[int] = Field(None, description="ID of source chain", title="Chain Id")
    wallet: Optional[str] = Field(
        None,
        description="Wallet-Address of original declaring party",
        example="0x1aD91ee08f21bE3dE0BA2ba6918E714dA6B45836",
        title="Wallet",
    )
    iscc_code: Optional[str] = Field(
        None,
        description="ISCC-CODE",
        example="KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY",
        max_length=73,
        min_length=15,
        regex="^[A-Z2-7]{10,73}$",
        title="Iscc Code",
    )


class Head(BaseModel):
    chain: int = Field(..., description="Source chain of the declaration", title="Chain")
    block_height: int = Field(..., description="N-th block on source ledger", title="Block Height")
    block_hash: str = Field(..., description="Hash of block", max_length=255, title="Block Hash")
    tx_idx: int = Field(
        ...,
        description="Index of transaction within block including the ISCC-DECLARATION",
        title="Transaction Index",
    )
    tx_hash: str = Field(
        ...,
        description="Hash of transaction that includes the ISCC-DECLARATION",
        max_length=255,
        title="Transaction Hash",
    )
    timestamp: datetime = Field(..., description="Block time of declaration", title="Timestamp")


class Message(BaseModel):
    message: str = Field(..., title="Message")


class RegistrationResponse(BaseModel):
    did: int = Field(
        ...,
        description="Cross-Chain time-ordered unique Declaration-ID",
        example=330445058337719994,
        title="Did",
    )
    iscc_id: str = Field(
        ...,
        description="Globally unique ISCC-ID",
        example="ISCC:MMAOHZYGQLBASTFM",
        max_length=73,
        min_length=15,
        regex="^ISCC:[A-Z2-7]{10,73}$",
        title="Iscc Id",
    )


class Declaration(BaseModel):
    timestamp: datetime = Field(..., description="Unix timestamp of block", title="Timestamp")
    chain_id: int = Field(..., description="ID of source chain", title="Chain Id")
    block_height: int = Field(..., description="Block height", title="Block Height")
    block_hash: str = Field(..., description="Block hash", title="Block Hash")
    tx_idx: int = Field(..., description="Index of TX within block", title="Tx Idx")
    tx_hash: str = Field(..., description="Hash of transaction", title="Tx Hash")
    declarer: str = Field(
        ..., description="Wallet-Address of original declaring party", title="Declarer"
    )
    iscc_code: str = Field(
        ...,
        description="ISCC-CODE without URI prefix",
        example="KACYPXW445FTYNJ3CYSXHAFJMA2HUWULUNRFE3BLHRSCXYH2M5AEGQY",
        max_length=73,
        min_length=15,
        regex="^[A-Z2-7:]{10,73}$",
        title="Iscc Code",
    )
    message: Optional[str] = Field(
        None, description="Declaration processing message", title="Message"
    )
    meta_url: Optional[str] = Field(None, description="URL for ISCC Metadata", title="Meta Url")
    registrar: Optional[str] = Field(
        None, description="Wallet-Address of registrar", title="Registrar"
    )
